[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "MrState"
version = "0.1"
description = "A random framework for wallclock-based events"
readme = "README.md"
requires-python = ">=3.8"
scripts = { MrState = "MrState:say_hello" }
